version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8443:443"
    volumes:
      - ./backend:/app
      - ./certs:/app/certs
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile/
      args:
        REACT_APP_API_URL: "https://localhost:8443"
    ports:
      - "3000:443"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge